
spring:
  data:
    rest:
      base-path: /api

logging:
  level:
    course: DEBUG

---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/courseintegrator
    username: 
    password: 

server:
  port: 8443
  ssl:
    key-store: file:///home/jacob/.mykeys.jks
    key-store-password: 427henry2019
    key-alias: tomcat
    key-password: 432jacob2019

logging:
  level:
    course: WARN
